# Generated by Django 5.1.1 on 2024-11-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransactionLog',
        ),
    ]
