# Generated by Django 5.1.1 on 2024-11-07 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_receipt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
    ]
