# Generated by Django 5.1.1 on 2024-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0008_alter_product_category_alter_product_supplier'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('create_product', 'Can create product'), ('import_product', 'Can import product'), ('custom_view_product', 'Can custom view product'), ('update_product', 'Can update product'), ('custom_delete_product', 'Can custom_delete product')]},
        ),
    ]
