# Generated by Django 5.1.1 on 2024-10-17 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('create_product', 'Can create product'), ('import_product', 'Can import product'), ('custom_view_product', 'Can custom view product'), ('custom_update_product', 'Can custom update product'), ('custom_delete_product', 'Can custom delete product')]},
        ),
    ]
