# Generated by Django 5.1.1 on 2024-10-22 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0013_alter_customer_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('can_access_admin_dashboard', 'Can access the admin dashboard')],
            },
        ),
    ]
