# Generated by Django 5.1.1 on 2024-10-29 16:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0014_adminpermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('customer', models.CharField(max_length=100)),
                ('transaction_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies.sale')),
            ],
        ),
    ]
