# Generated by Django 5.1.1 on 2024-10-30 13:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0015_transactionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='sales_reference',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
